//
// Here you can control what scene will be loaded.
//

#include <sb6.h>

#include "DeferredShading.cpp" // Yep, looks like shit, but framework force to do like this.
#include "GeomShaders/Explode.cpp"
#include "GeomShaders/GeomShadersCulling.cpp"
#include "GeomShaders/GSTesselation.cpp"
#include "GeomShaders/Multiviewport.cpp"
#include "GeomShaders/NormalViewer.cpp"
#include "GeomShaders/QuadPainter.cpp"
#include "Tesselation/Terrain.cpp"
#include "Tesselation/TessAndGeom.cpp"
#include "Tesselation/TessCube.cpp"
#include "Tesselation/TessModes.cpp"
#include "Tesselation/TessSubdivisionModes.cpp"
#include "Tesselation/TessTest.cpp"
#include "Tesselation/TessTrigs.cpp"
#include "AlienRain.cpp"
#include "Bezier.cpp"
#include "Bloom.cpp"
#include "BumpMap.cpp"
#include "Cellshading.cpp"
#include "ColorBlend.cpp"
#include "CubemapEnv.cpp"
#include "Cubes.cpp"
#include "CusomClipping.cpp"
#include "DepthClamp.cpp"
#include "DepthOfField.cpp"
#include "Dummy.cpp"
#include "Exposure.cpp"
#include "FBOLayeredTex.cpp"
#include "Flocking.cpp"
#include "Glossmap.cpp"
#include "GrassInstancing.cpp"
#include "IndirectDraw.cpp"
#include "IndirectMultidrawSimple.cpp"
#include "InstancingDivisor.cpp"
#include "JuliaFractal.cpp"
#include "LineSmoothing.cpp"
#include "Multiscissor.cpp"
#include "NativeMSAA.cpp"
#include "NoPerspective.cpp"
#include "PrefixSum.cpp"
#include "PrefixSum2D.cpp"
#include "PrimitiveRestart.cpp"
#include "RectEnvMap.cpp"
#include "RenderToTex.cpp"
#include "RimLight.cpp"
#include "SampleShading.cpp"
#include "SeparateShaderPipeline.cpp"
#include "ShaderInfo.cpp"
#include "ShadowMapping.cpp"
#include "ShapedPoints.cpp"
#include "SphereEnvMap.cpp"
#include "Subroutines.cpp"
#include "Textures.cpp"
#include "Tonemapping.cpp"
#include "TransformFeedback.cpp"
#include "TransformFeedbackParticles.cpp"

class SceneStarter : public sb6::application
{    
};
DECLARE_MAIN(OpenGlSB::DeferredShading);